/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AstrologyRouteImport } from './routes/astrology'
import { Route as AnimalFactsRouteImport } from './routes/animal-facts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as ApiSubstackRouteImport } from './routes/api/substack'
import { Route as ApiPinterestRouteImport } from './routes/api/pinterest'
import { Route as ApiInstagramRouteImport } from './routes/api/instagram'
import { Route as ApiHoroscopeRouteImport } from './routes/api/horoscope'
import { Route as ApiFunFactRouteImport } from './routes/api/fun-fact'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiAstrologyTransitsRouteImport } from './routes/api/astrology-transits'
import { Route as ApiAnimalFactRouteImport } from './routes/api/animal-fact'
import { Route as ApiSpotifyTopTracksRouteImport } from './routes/api/spotify/top-tracks'
import { Route as ApiSpotifyRecentlyPlayedRouteImport } from './routes/api/spotify/recently-played'
import { Route as ApiSpotifyNowPlayingRouteImport } from './routes/api/spotify/now-playing'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologyRoute = AstrologyRouteImport.update({
  id: '/astrology',
  path: '/astrology',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalFactsRoute = AnimalFactsRouteImport.update({
  id: '/animal-facts',
  path: '/animal-facts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const ApiSubstackRoute = ApiSubstackRouteImport.update({
  id: '/api/substack',
  path: '/api/substack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPinterestRoute = ApiPinterestRouteImport.update({
  id: '/api/pinterest',
  path: '/api/pinterest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInstagramRoute = ApiInstagramRouteImport.update({
  id: '/api/instagram',
  path: '/api/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHoroscopeRoute = ApiHoroscopeRouteImport.update({
  id: '/api/horoscope',
  path: '/api/horoscope',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFunFactRoute = ApiFunFactRouteImport.update({
  id: '/api/fun-fact',
  path: '/api/fun-fact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAstrologyTransitsRoute = ApiAstrologyTransitsRouteImport.update({
  id: '/api/astrology-transits',
  path: '/api/astrology-transits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnimalFactRoute = ApiAnimalFactRouteImport.update({
  id: '/api/animal-fact',
  path: '/api/animal-fact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyTopTracksRoute = ApiSpotifyTopTracksRouteImport.update({
  id: '/api/spotify/top-tracks',
  path: '/api/spotify/top-tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyRecentlyPlayedRoute =
  ApiSpotifyRecentlyPlayedRouteImport.update({
    id: '/api/spotify/recently-played',
    path: '/api/spotify/recently-played',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSpotifyNowPlayingRoute = ApiSpotifyNowPlayingRouteImport.update({
  id: '/api/spotify/now-playing',
  path: '/api/spotify/now-playing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/animal-facts': typeof AnimalFactsRoute
  '/astrology': typeof AstrologyRoute
  '/gallery': typeof GalleryRoute
  '/journal': typeof JournalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/api/animal-fact': typeof ApiAnimalFactRoute
  '/api/astrology-transits': typeof ApiAstrologyTransitsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/fun-fact': typeof ApiFunFactRoute
  '/api/horoscope': typeof ApiHoroscopeRoute
  '/api/instagram': typeof ApiInstagramRoute
  '/api/pinterest': typeof ApiPinterestRoute
  '/api/substack': typeof ApiSubstackRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/api/spotify/now-playing': typeof ApiSpotifyNowPlayingRoute
  '/api/spotify/recently-played': typeof ApiSpotifyRecentlyPlayedRoute
  '/api/spotify/top-tracks': typeof ApiSpotifyTopTracksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/animal-facts': typeof AnimalFactsRoute
  '/astrology': typeof AstrologyRoute
  '/gallery': typeof GalleryRoute
  '/journal': typeof JournalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/api/animal-fact': typeof ApiAnimalFactRoute
  '/api/astrology-transits': typeof ApiAstrologyTransitsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/fun-fact': typeof ApiFunFactRoute
  '/api/horoscope': typeof ApiHoroscopeRoute
  '/api/instagram': typeof ApiInstagramRoute
  '/api/pinterest': typeof ApiPinterestRoute
  '/api/substack': typeof ApiSubstackRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/api/spotify/now-playing': typeof ApiSpotifyNowPlayingRoute
  '/api/spotify/recently-played': typeof ApiSpotifyRecentlyPlayedRoute
  '/api/spotify/top-tracks': typeof ApiSpotifyTopTracksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/animal-facts': typeof AnimalFactsRoute
  '/astrology': typeof AstrologyRoute
  '/gallery': typeof GalleryRoute
  '/journal': typeof JournalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/api/animal-fact': typeof ApiAnimalFactRoute
  '/api/astrology-transits': typeof ApiAstrologyTransitsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/fun-fact': typeof ApiFunFactRoute
  '/api/horoscope': typeof ApiHoroscopeRoute
  '/api/instagram': typeof ApiInstagramRoute
  '/api/pinterest': typeof ApiPinterestRoute
  '/api/substack': typeof ApiSubstackRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/api/spotify/now-playing': typeof ApiSpotifyNowPlayingRoute
  '/api/spotify/recently-played': typeof ApiSpotifyRecentlyPlayedRoute
  '/api/spotify/top-tracks': typeof ApiSpotifyTopTracksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/animal-facts'
    | '/astrology'
    | '/gallery'
    | '/journal'
    | '/privacy'
    | '/api/animal-fact'
    | '/api/astrology-transits'
    | '/api/contact'
    | '/api/fun-fact'
    | '/api/horoscope'
    | '/api/instagram'
    | '/api/pinterest'
    | '/api/substack'
    | '/journal/$slug'
    | '/api/spotify/now-playing'
    | '/api/spotify/recently-played'
    | '/api/spotify/top-tracks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/animal-facts'
    | '/astrology'
    | '/gallery'
    | '/journal'
    | '/privacy'
    | '/api/animal-fact'
    | '/api/astrology-transits'
    | '/api/contact'
    | '/api/fun-fact'
    | '/api/horoscope'
    | '/api/instagram'
    | '/api/pinterest'
    | '/api/substack'
    | '/journal/$slug'
    | '/api/spotify/now-playing'
    | '/api/spotify/recently-played'
    | '/api/spotify/top-tracks'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/animal-facts'
    | '/astrology'
    | '/gallery'
    | '/journal'
    | '/privacy'
    | '/api/animal-fact'
    | '/api/astrology-transits'
    | '/api/contact'
    | '/api/fun-fact'
    | '/api/horoscope'
    | '/api/instagram'
    | '/api/pinterest'
    | '/api/substack'
    | '/journal/$slug'
    | '/api/spotify/now-playing'
    | '/api/spotify/recently-played'
    | '/api/spotify/top-tracks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnimalFactsRoute: typeof AnimalFactsRoute
  AstrologyRoute: typeof AstrologyRoute
  GalleryRoute: typeof GalleryRoute
  JournalRoute: typeof JournalRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ApiAnimalFactRoute: typeof ApiAnimalFactRoute
  ApiAstrologyTransitsRoute: typeof ApiAstrologyTransitsRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiFunFactRoute: typeof ApiFunFactRoute
  ApiHoroscopeRoute: typeof ApiHoroscopeRoute
  ApiInstagramRoute: typeof ApiInstagramRoute
  ApiPinterestRoute: typeof ApiPinterestRoute
  ApiSubstackRoute: typeof ApiSubstackRoute
  ApiSpotifyNowPlayingRoute: typeof ApiSpotifyNowPlayingRoute
  ApiSpotifyRecentlyPlayedRoute: typeof ApiSpotifyRecentlyPlayedRoute
  ApiSpotifyTopTracksRoute: typeof ApiSpotifyTopTracksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrology': {
      id: '/astrology'
      path: '/astrology'
      fullPath: '/astrology'
      preLoaderRoute: typeof AstrologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animal-facts': {
      id: '/animal-facts'
      path: '/animal-facts'
      fullPath: '/animal-facts'
      preLoaderRoute: typeof AnimalFactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/api/substack': {
      id: '/api/substack'
      path: '/api/substack'
      fullPath: '/api/substack'
      preLoaderRoute: typeof ApiSubstackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pinterest': {
      id: '/api/pinterest'
      path: '/api/pinterest'
      fullPath: '/api/pinterest'
      preLoaderRoute: typeof ApiPinterestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/instagram': {
      id: '/api/instagram'
      path: '/api/instagram'
      fullPath: '/api/instagram'
      preLoaderRoute: typeof ApiInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/horoscope': {
      id: '/api/horoscope'
      path: '/api/horoscope'
      fullPath: '/api/horoscope'
      preLoaderRoute: typeof ApiHoroscopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fun-fact': {
      id: '/api/fun-fact'
      path: '/api/fun-fact'
      fullPath: '/api/fun-fact'
      preLoaderRoute: typeof ApiFunFactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/astrology-transits': {
      id: '/api/astrology-transits'
      path: '/api/astrology-transits'
      fullPath: '/api/astrology-transits'
      preLoaderRoute: typeof ApiAstrologyTransitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/animal-fact': {
      id: '/api/animal-fact'
      path: '/api/animal-fact'
      fullPath: '/api/animal-fact'
      preLoaderRoute: typeof ApiAnimalFactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/top-tracks': {
      id: '/api/spotify/top-tracks'
      path: '/api/spotify/top-tracks'
      fullPath: '/api/spotify/top-tracks'
      preLoaderRoute: typeof ApiSpotifyTopTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/recently-played': {
      id: '/api/spotify/recently-played'
      path: '/api/spotify/recently-played'
      fullPath: '/api/spotify/recently-played'
      preLoaderRoute: typeof ApiSpotifyRecentlyPlayedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/now-playing': {
      id: '/api/spotify/now-playing'
      path: '/api/spotify/now-playing'
      fullPath: '/api/spotify/now-playing'
      preLoaderRoute: typeof ApiSpotifyNowPlayingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnimalFactsRoute: AnimalFactsRoute,
  AstrologyRoute: AstrologyRoute,
  GalleryRoute: GalleryRoute,
  JournalRoute: JournalRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ApiAnimalFactRoute: ApiAnimalFactRoute,
  ApiAstrologyTransitsRoute: ApiAstrologyTransitsRoute,
  ApiContactRoute: ApiContactRoute,
  ApiFunFactRoute: ApiFunFactRoute,
  ApiHoroscopeRoute: ApiHoroscopeRoute,
  ApiInstagramRoute: ApiInstagramRoute,
  ApiPinterestRoute: ApiPinterestRoute,
  ApiSubstackRoute: ApiSubstackRoute,
  ApiSpotifyNowPlayingRoute: ApiSpotifyNowPlayingRoute,
  ApiSpotifyRecentlyPlayedRoute: ApiSpotifyRecentlyPlayedRoute,
  ApiSpotifyTopTracksRoute: ApiSpotifyTopTracksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
